### ISSUE TITLE
I cannot install with "pip3 install weconnect[Images]"

### ISSUE THREAD

**Issue by Jambo52** [tillsteinbach/WeConnect-python#151]
At the end of the installation the following appears:

During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-install-g0jhbug7/pillow_821b0937fbe04c219ea2c6ed95f8bcdb/_custom_build/backend.py", line 53, in build_wheel
          return super().build_wheel(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-sdn9vph1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-sdn9vph1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-install-g0jhbug7/pillow_821b0937fbe04c219ea2c6ed95f8bcdb/_custom_build/backend.py", line 47, in run_setup
          return super().run_setup(setup_script)
        File "/tmp/pip-build-env-sdn9vph1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1005, in <module>
      __main__.RequiredDependencyException:

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
pi@raspberrypi:~ $

I uninstalled pip, pip3, python and pillow and reinstalled everything, but I always get this message. What am I doing wrong?
Greetings from Cologne
Norbert

**Comment by tillsteinbach** [comment]
Pillow needs a library for handling jpegs, you probably only need to install libjpeg
