### ISSUE TITLE
Login error - OAuth 2 MUST utilize https.

### ISSUE THREAD

**Issue by flaviobattimo** [tillsteinbach/WeConnect-python#216]
Hello, I'm recently getting this issue when trying to login.
Using weconnect-cli to reproduce the issue but I'm getting the same with weconnect-python

**Logs**
Traceback (most recent call last):
  File "/home/pi/.local/bin/weconnect-cli", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect_cli/weconnect_cli_base.py", line 205, in main
    weConnect.login()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

Login Traceback (most recent call last): 
File ".../weconnect/weconnect.py", line 184, in login self.__session.login() 
File ".../weconnect/auth/we_connect_session.py", line 76, in login response = self.doWebAuth(authorizationUrl) 
File ".../weconnect/auth/we_connect_session.py", line 253, in doWebAuth afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE) 
File ".../requests/sessions.py", line 602, in get return self.request("GET", url, **kwargs) 
File ".../weconnect/auth/we_connect_session.py", line 69, in request return super(WeConnectSession, self).request( 
File ".../weconnect/auth/openid_session.py", line 188, in request raise InsecureTransportError() oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

Thanks,
Flavio

 - Version used: weconnect-0.60.5

**Comment by HertogArjan** [comment]
> You probably need to accept the new terms and conditions. Try logging out and in again in the app or web.

This worked for me. Logged into the web. I had to enter my country of residence because of an updated privacy policy.

**Comment by flaviobattimo** [comment]
thanks, I hadn't tried to log in. It works perfectly.
