### ISSUE TITLE
OAuth 2 error

### ISSUE THREAD

**Issue by EckhardM** [tillsteinbach/WeConnect-python#217]
allVehicles.py creates an OAuth 2 error:

```
#  Initialize WeConnect
#  Login
Traceback (most recent call last):
  File "/home/malc/WeConnect-python/examples/allVehicles.py", line 30, in <module>
    main()
  File "/home/malc/WeConnect-python/examples/allVehicles.py", line 19, in main
    weConnect.login()
  File "/home/malc/venv/lib/python3.11/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/home/malc/venv/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malc/venv/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malc/venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malc/venv/lib/python3.11/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malc/venv/lib/python3.11/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

**Comment by tillsteinbach** [comment]
Please logout and In again in the Volkswagen app and accept the new terms and conditions

**Comment by EckhardM** [comment]
Amazing - thank you, it works!
