### ISSUE TITLE
 APICompatibilityError('No credentials form found') in 0.35 and 0.34

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#33]
Since this morning i get the following error when loggin in/update. 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 771, in fetchData
    self.login()
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 391, in login
    raise APICompatibilityError('No credentials form found')
weconnect.errors.APICompatibilityError: No credentials form found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 35, in async_setup_entry
    await hass.async_add_executor_job(api.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 594, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 601, in updateVehicles
    data = self.fetchData(url, force)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 797, in fetchData
    except requests.exceptions.JSONDecodeError as jsonError:
AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'`

**Comment by tillsteinbach** [comment]
VW changed the login form. Will release an update as soon as possible!

**Comment by tillsteinbach** [comment]
I have a dirty emergency fix out in 0.35.1 I will make it more beautiful the next days. At least it should work again!

**Comment by mitch-dc** [comment]
Thank you very much! Also from a lot of home assistant users ;)

**Comment by strutings** [comment]
Good job! Thanks
