### ISSUE TITLE
Login is changed _again_

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#39]
`2022-02-11 10:40:19 ERROR (MainThread) [homeassistant.components.volkswagen_we_connect_id.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/workspaces/core/homeassistant/components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 166, in login
    self.__session.login()
  File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 49, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 140, in doWebAuth
    raise APICompatibilityError('No credentials form found')
weconnect.errors.APICompatibilityError: No credentials form found`

I'm using the newest version #0.36.2

**Comment by tillsteinbach** [comment]
Damn! Quite fragile at the moment :( Will have a look asap
