### ISSUE TITLE
Unknown attribute log messages

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#40]
**Describe the bug**
Got a lot of warning messages

**Logs**

```
2022-02-16 13:57:01 WARNING (SyncWorker_5) [weconnect] /vehicles/WVGZZZE2ZMP053387/domains/charging/chargingStatus: Unknown attribute chargeType with value invalid
2022-02-16 13:57:01 WARNING (SyncWorker_5) [weconnect] /vehicles/WVGZZZE2ZMP053387/domains/charging/chargingStatus: Unknown attribute chargingSettings with value default
```

**Comment by tillsteinbach** [comment]
Yes, VW extended the interface again. Will add this as soon as I understood what possible values there are.

**Comment by mitch-dc** [comment]
Any idea when you can add these attributes? I've tried the beta/alpha version, the new attributes are added but other things stopped working.

**Comment by tillsteinbach** [comment]
In theory I can release 0.37.0 tonight. But what kind of thing stopped working? That would be a reason not to release.

**Comment by mitch-dc** [comment]
```2022-02-23 19:01:43 ERROR (MainThread) [homeassistant.components.volkswagen_we_connect_id] Unexpected error fetching volkswagen_we_connect_id data: 'float' object has no attribute 'fromDict'
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/workspaces/core/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/workspaces/core/homeassistant/components/volkswagen_we_connect_id/__init__.py", line 46, in async_update_data
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 175, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.9/site-packages/weconnect/weconnect.py", line 198, in updateVehicles
    self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures,
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 197, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements/vehicle.py", line 288, in updateStatus
    self.domains[domain.value][key].update(fromDict=data[domain.value][key])
  File "/usr/local/lib/python3.9/site-packages/weconnect/elements/climatization_settings.py", line 75, in update
    self.targetTemperature_C.fromDict(fromDict['value'], 'targetTemperature_C')
AttributeError: 'float' object has no attribute 'fromDict'```


After setting the target temperature

**Comment by tillsteinbach** [comment]
hmmm, can you show the code where you set the temperature?

**Comment by mitch-dc** [comment]
```
 try:
    vehicle.domains["climatisation"][
        "climatisationSettings"
    ].targetTemperature_C = target_temperature
    _LOGGER.info("Sended target temperature call to the car")
except Exception as exc:
    _LOGGER.error("Failed to send request to car - %s", exc)
    return False
```

**Comment by tillsteinbach** [comment]
you have to change
`targetTemperature_C = target_temperature` to
`targetTemperature_C.value = target_temperature`

**Comment by mitch-dc** [comment]
Then i got 

```
Failed to send request to car - 'type' object is not iterable
```

**Comment by tillsteinbach** [comment]
that is a bug!

**Comment by tillsteinbach** [comment]
You can try `0.37.0.dev5`

**Comment by mitch-dc** [comment]
That's a fast bugfix, will try it right now ;)

**Comment by mitch-dc** [comment]
Hmm i don't think it sets the value right now

**Comment by tillsteinbach** [comment]
Can you see what the request status is? When I open the ID app I see an error message and when I try to set the value I get the request status `Request: start operation, status polling_timeout  information: Your vehicle is not reachable at the moment. Please try again later. Request Id: e654a0b5-24b1-4907-b8d7-f3e080e6e5a7` after a while.

**Comment by mitch-dc** [comment]
hmm yea i got issues with the app as well today. So maby Volkswagen is doing stuff again...

**Comment by tillsteinbach** [comment]
Maybe a good idea to delay the release to tomorrow and check if its works again :)

**Comment by mitch-dc** [comment]
Yeah wil check tomorrow! Thanks for you time ;)

**Comment by tillsteinbach** [comment]
0.37.0 was just released
