### ISSUE TITLE
Error during login, account X does not exist

### ISSUE THREAD

**Issue by drew-hill** [tillsteinbach/WeConnect-python#97]
**Describe the bug**

Using `weconnect.WeConnect(username=<username>, password=<password>)`, with an appropriate and verified username and password, I get the errors:

**To Reproduce**
1. Open Python 3.10.6 in terminal.
2. Run `from weconnect import weconnect`
3. Run `weconnect.WeConnect(username=<username>, password=<password>)`, with an appropriate and verified username and password
5. See error

**Logs**
```
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 115, in init
self.update(updateCapabilities=updateCapabilities, updatePictures=updatePictures, selective=selective)
File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 191, in update
self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 199, in updateVehicles
data = self.fetchData(url, force)
File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 364, in fetchData
statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
return self.request("GET", url, **kwargs)
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
return super(WeConnectSession, self).request(
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/openid_session.py", line 192, in request
url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/openid_session.py", line 229, in addToken
self.login()
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
response = self.doWebAuth(authorizationUrl)
File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 198, in doWebAuth
raise AuthentificationError(f'Error during login, account {self.sessionuser.username} does not exist')
weconnect.errors.AuthentificationError: Error during login, account <redacted> does not exist
```

 - OS: Mac OS 13.1
 - v 0.51.0

**Additional context**
Original error was observed using a Home Assistant integration that uses the WeConnect-python library: https://github.com/mitch-dc/volkswagen_we_connect_id

Could this all simply be because I am in the US and using Car-Net? I assumed the rebranding of WeConnect to Car-Net wouldn't matter, but this may be a stupid assumption.

**Comment by tillsteinbach** [comment]
Unfortunately your last assumption is correct. WeConnect is not a rebranding of car-net and uses a different backend. Unfortunately there is nothing so can do today.

**Comment by drew-hill** [comment]
Makes perfect sense. Thanks very kindly for clearing that up for me!
